### ISSUE TITLE
Minio vs Memory Pinning

### ISSUE THREAD

**Issue by yanniszark** [msr-fiddle/DS-Analyzer#2]
Great work on the data stalls paper!
Reading the paper, I was wondering what is the advantage of using a simple non-evicting cache (minio) vs pinning part of the dataset in-memory.
I didn't find any mention of this alternative in the paper.

**Comment by jayashreemohan29** [comment]
Memory pinning can be used to implement MinIO. The idea behind MinIO is to cache a set of data items that would result in uniform cache hits throughout the epoch rather than skewing hits to a certain access range. While MinIO is currently implemented using shared memory files, it can also be done using memory pinning. Happy to chat more over email.
